package felipemandu.com.br.mangaappstudy.entity

enum class GenreEnum(genre: String) {
    ACTION("Action"),
    ADVENTURE("Adventure"),
    CARS("Cars"),
    COMEDY("Comedy"),
    DEMENTIA("Dementia"),
    DEMONS("Demons"),
    DOUJINSHI("Doujinshi"),
    DRAMA("Drama"),
    ECCHI("Ecchi"),
    FANTASY("Fantasy"),
    GAME("Game"),
    GENDER_BENDER("Gender Bender"),
    HAREM("Harem"),
    HENTAI("Hentai"),
    HISTORICAL("Historical"),
    HORROR("Horror"),
    JOSEI("Josei"),
    KIDS("Kids"),
    MAGIC("Magic"),
    MARTIAL_ARTS("Martial Arts"),
    MECHA("Mecha"),
    MILITARY("Military"),
    MUSIC("Music"),
    MYSTERY("Mystery"),
    PARODY("Parody"),
    POLICE("Police"),
    PSYCHOLOGICAL("Psychological"),
    ROMANCE("Romance"),
    SAMURAI("Samurai"),
    SCHOOL("School"),
    SCI_FI(" Sci-fi"),
    SEINEN("Seinen"),
    SHOUJO("Shoujo"),
    SHOUJO_AI("Shoujo Ai"),
    SHOUNEN("Shounen"),
    SHOUNEN_AI("Shounen Ai"),
    SLICE_OF_LIFE("Slice Of Life"),
    SPACE("Space"),
    SPORTS("Sports"),
    SUPER_POWER("Super Power"),
    SUPERNATURAL("Supernatural"),
    THRILLER("Thriller"),
    VAMPIRE("Vampire"),
    YAOI("Yaoi"),
    YURI ("Yuri")
}