spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
    data:
      classpath: schema.sql, data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

logging:
  level:
    web: DEBUG