CREATE TABLE IF NOT EXISTS COUNTRY (
	COUNTRY_ID BIGINT NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	PRIMARY KEY (COUNTRY_ID),
	CONSTRAINT UK_COUNTRY UNIQUE (NAME)
);


CREATE TABLE IF NOT EXISTS GENRE (
	GENRE_ID BIGINT NOT NULL, 
	GENRE VARCHAR(255), 
	PRIMARY KEY (GENRE_ID),
	CONSTRAINT UK_GENRE UNIQUE (GENRE)
);

CREATE TABLE IF NOT EXISTS LANGUAGE (
	LANGUAGE_ID BIGINT NOT NULL, 
	LANGUAGE VARCHAR(255) NOT NULL, 
	PRIMARY KEY (LANGUAGE_ID),
	CONSTRAINT UK_LANGUAGE UNIQUE (LANGUAGE)
);

CREATE TABLE IF NOT EXISTS AUTHOR (
	AUTHOR_ID BIGINT NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	COUNTRY_ID BIGINT, 
	PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS HOSTING_WEBSITE (
	HOSTING_WEBSITE_ID BIGINT NOT NULL, 
	NAME VARCHAR(255) NOT NULL, 
	LANGUAGE_ID BIGINT NOT NULL,
	PRIMARY KEY (HOSTING_WEBSITE_ID)
);


CREATE TABLE IF NOT EXISTS LANGUAGE_COUNTRY (
	LANGUAGE_ID BIGINT NOT NULL, 
	COUNTRY_ID BIGINT NOT NULL, 
	PRIMARY KEY (LANGUAGE_ID, COUNTRY_ID)
);


CREATE TABLE IF NOT EXISTS LANGUAGE_HOSTING_WEBSITE (
	LANGUAGE_ID BIGINT NOT NULL, 
	HOSTING_WEBSITE_ID BIGINT NOT NULL, 
	PRIMARY KEY (LANGUAGE_ID, HOSTING_WEBSITE_ID)	
);


CREATE TABLE IF NOT EXISTS CHAPTER (
	CHAPTER_ID BIGINT NOT NULL, 
	ISBN VARCHAR(255), 
	CHAPTER_NUMBER INTEGER, 
	NUMBER_PAGES INTEGER, 
	NUMBER_VISUALIZATION INTEGER, 
	RELEASE TIMESTAMP, 
	TITLE VARCHAR(255), 
	MANGA_ID BIGINT, 
	PRIMARY KEY (CHAPTER_ID)
);


CREATE TABLE IF NOT EXISTS MANGA (
	MANGA_ID BIGINT NOT NULL, 
	DESCRIPTION VARCHAR(255), 
	LAST_CHAPTER TIMESTAMP, 
	RATING INTEGER, 
	RELEASE TIMESTAMP, 
	STATUS VARCHAR(255) NOT NULL, 
	TITLE VARCHAR(255) NOT NULL, 
	HOSTING_WEBSITE_ID BIGINT,
	COUNTRY_ID BIGINT, 
	ORIGIN_LANGUAGE_ID BIGINT, 
	TRANSLATED_LANGUAGE_ID BIGINT, 
	PRIMARY KEY (MANGA_ID)
);


CREATE TABLE IF NOT EXISTS MANGA_AUTHOR (
	MANGA_ID BIGINT NOT NULL, 
	AUTHOR_ID BIGINT NOT NULL, 
	PRIMARY KEY (MANGA_ID, AUTHOR_ID)
);




CREATE TABLE IF NOT EXISTS MANGA_GENRE (
	MANGA_ID BIGINT NOT NULL, 
	GENRE_ID BIGINT NOT NULL, 
	PRIMARY KEY (MANGA_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PAGES (
	CHAPTER_ID BIGINT NOT NULL, 
	PAGES VARCHAR(255)
);



ALTER TABLE LANGUAGE_COUNTRY DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_LANGUAGE_COUNTRY;
ALTER TABLE LANGUAGE_COUNTRY DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_COUNTRY_LANGUAGE;
ALTER TABLE HOSTING_WEBSITE DROP CONSTRAINT IF EXISTS FK_HOSTING_WEBSITE_LANGUAGE;
ALTER TABLE AUTHOR DROP CONSTRAINT IF EXISTS FK_COUNTRY_AUTHOR;
ALTER TABLE CHAPTER DROP CONSTRAINT IF EXISTS FK_MANGA_CHAPTER;
ALTER TABLE MANGA DROP CONSTRAINT IF EXISTS FK_COUNTRY_MANGA;
ALTER TABLE MANGA DROP CONSTRAINT IF EXISTS FK_HOSTING_WEBSITE_MANGA;
ALTER TABLE MANGA DROP CONSTRAINT IF EXISTS FK_ORIGIN_LANGUAGE_MANGA;
ALTER TABLE MANGA DROP CONSTRAINT IF EXISTS FK_TRANSLATED_LANGUAGE_MANGA;
ALTER TABLE MANGA_AUTHOR DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_AUTHOR_MANGA;
ALTER TABLE MANGA_AUTHOR DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_MANGA_AUTHOR;
ALTER TABLE MANGA_GENRE DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_GENRE_MANGA;
ALTER TABLE MANGA_GENRE DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_MANGA_GENRE;
ALTER TABLE PAGES DROP CONSTRAINT IF EXISTS FK_CHAPTER_PAGES;
ALTER TABLE LANGUAGE_HOSTING_WEBSITE DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_HOSTING_WEBSITE_LANGUAGE;
ALTER TABLE LANGUAGE_HOSTING_WEBSITE DROP CONSTRAINT IF EXISTS FK_MANY_TO_MANY_LANGUAGE_HOSTING_WEBSITE;


ALTER TABLE LANGUAGE_COUNTRY ADD CONSTRAINT FK_MANY_TO_MANY_LANGUAGE_COUNTRY FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE;
ALTER TABLE LANGUAGE_COUNTRY ADD CONSTRAINT FK_MANY_TO_MANY_COUNTRY_LANGUAGE FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY;
ALTER TABLE HOSTING_WEBSITE ADD CONSTRAINT FK_HOSTING_WEBSITE_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE;
ALTER TABLE AUTHOR ADD CONSTRAINT FK_COUNTRY_AUTHOR FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY;
ALTER TABLE CHAPTER ADD CONSTRAINT FK_MANGA_CHAPTER FOREIGN KEY (MANGA_ID) REFERENCES MANGA;
ALTER TABLE MANGA ADD CONSTRAINT FK_COUNTRY_MANGA FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY;
ALTER TABLE MANGA ADD CONSTRAINT FK_HOSTING_WEBSITE_MANGA FOREIGN KEY (HOSTING_WEBSITE_ID) REFERENCES HOSTING_WEBSITE;
ALTER TABLE MANGA ADD CONSTRAINT FK_ORIGIN_LANGUAGE_MANGA FOREIGN KEY (ORIGIN_LANGUAGE_ID) REFERENCES LANGUAGE;
ALTER TABLE MANGA ADD CONSTRAINT FK_TRANSLATED_LANGUAGE_MANGA FOREIGN KEY (TRANSLATED_LANGUAGE_ID) REFERENCES LANGUAGE;
ALTER TABLE MANGA_AUTHOR ADD CONSTRAINT FK_MANY_TO_MANY_AUTHOR_MANGA FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR;
ALTER TABLE MANGA_AUTHOR ADD CONSTRAINT FK_MANY_TO_MANY_MANGA_AUTHOR FOREIGN KEY (MANGA_ID) REFERENCES MANGA;
ALTER TABLE MANGA_GENRE ADD CONSTRAINT FK_MANY_TO_MANY_GENRE_MANGA FOREIGN KEY (GENRE_ID) REFERENCES GENRE;
ALTER TABLE MANGA_GENRE ADD CONSTRAINT FK_MANY_TO_MANY_MANGA_GENRE FOREIGN KEY (MANGA_ID) REFERENCES MANGA;
ALTER TABLE PAGES ADD CONSTRAINT FK_CHAPTER_PAGES FOREIGN KEY (CHAPTER_ID) REFERENCES CHAPTER;
ALTER TABLE LANGUAGE_HOSTING_WEBSITE ADD CONSTRAINT FK_MANY_TO_MANY_HOSTING_WEBSITE_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE;
ALTER TABLE LANGUAGE_HOSTING_WEBSITE ADD CONSTRAINT FK_MANY_TO_MANY_LANGUAGE_HOSTING_WEBSITE FOREIGN KEY (HOSTING_WEBSITE_ID) REFERENCES HOSTING_WEBSITE;








